name: Markdown Document Checks

on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Vale for English and Style Check
        uses: errata-ai/vale-action@v2.1.1
        with:
          files: "*.md"

      - name: Markdownlint Check
        uses: davidanson/markdownlint-cli2-action@v1
        with:
          files: "*.md"

      - name: Run Gitleaks for Secrets Detection
        uses: zricethezav/gitleaks-action@v1
        with:
          config: gitleaks.toml

      - name: Proselint for Grammar and Style
        run: |
          proselint README.md
